[auth]
password = 'password123'
username = 'admin'

[database]
host = '18.167.72.137'
name = 'test'
password = '123'
port = '3306'
user = 't1'

[port]
max = 30000
min = 10000

[server]
addr = '0.0.0.0:8080'
updateintervalhours = 24
